# To build the entire stack run 'make run'

services:
  tarkov_data_manager:
    container_name: tarkov_data_manager
    restart: unless-stopped
    build:
      context: ./src/tarkov-data-manager
      dockerfile: ./Dockerfile
    env_file: 
      - ./src/tarkov-data-manager/config.env
      - ./src/tarkov-data-manager/creds.env
    ports:
      - 4000:4000
    volumes:
      - ./src/tarkov-data-manager/settings:/app/settings
      - ./src/tarkov-data-manager/cache:/app/cache
      - ./src/tarkov-data-manager/logs:/app/logs
      - ./src/tarkov-data-manager/dumps:/app/dumps
      - ./src/tarkov-data-manager/node-logs:/home/node/.npm/_logs
    depends_on:
      - primary
      - replica
      - db_proxy

  # the primary node for the libsql database
  primary:
    # https://github.com/tursodatabase/libsql/pkgs/container/libsql-server/184665658?tag=v0.23.4
    build:
      context: ./src/libsql
      dockerfile: ./Dockerfile
    env_file: 
      - ./src/libsql/creds.env
    environment:
      - SQLD_NODE="primary"
      - SQLD_HTTP_LISTEN_ADDR=0.0.0.0:8081
      - SQLD_GRPC_LISTEN_ADDR=0.0.0.0:5001
      - SQLD_ENABLE_BOTTOMLESS_REPLICATION=true # set this to false if you are doing local dev work unless you want to sync with the production database
      - LIBSQL_BOTTOMLESS_AWS_DEFAULT_REGION=us-east-1
      - LIBSQL_BOTTOMLESS_BUCKET=the-hideout-libsql
    ports:
      - "8081:8081" # HTTP API
      - "5001:5001" # gRPC API
    volumes:
      - libsql_data:/var/lib/sqld
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # the replica node for the libsql database
  replica:
    # https://github.com/tursodatabase/libsql/pkgs/container/libsql-server/184665658?tag=v0.23.4
    build:
      context: ./src/libsql
      dockerfile: ./Dockerfile
    environment:
      - SQLD_NODE=replica
      - SQLD_PRIMARY_URL=http://primary:5001
      - SQLD_HTTP_LISTEN_ADDR=0.0.0.0:8082
    depends_on:
      - primary
    volumes:
      - libsql_data:/var/lib/sqld
    ports:
      - "8082:8082" # HTTP API
      - "5002:5002" # gRPC API
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  db_proxy:
    image: nginx:1.25.4
    volumes:
      - ./src/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - replica
    ports:
      - "6002:6002"
      - "8080:8080"

  caddy:
    container_name: caddy-service
    restart: unless-stopped
    build:
      context: ./src/caddy
      dockerfile: ./Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/caddy_data:/data
      - ./data/caddy_config:/config
    depends_on:
      - tarkov_data_manager
    environment:
      PROXY_BACKEND: tarkov_data_manager
      PROXY_PORT: 4000
      DOMAIN: ${DOMAIN}

  # a dev container that has curl on a basic ubuntu image
  curl:
    image: curlimages/curl:latest
    command: ["tail", "-f", "/dev/null"]

volumes:
  caddy_data:
  caddy_config:
  settings:
  cache:
  logs:
  dumps:
  libsql_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./data/libsql_data
