#!/bin/bash

sudo cp /etc/letsencrypt/live/manager.thehideout.io/privkey.pem ~/tarkov-data-manager/src/nginx/ssl/
sudo cp /etc/letsencrypt/live/manager.thehideout.io/fullchain.pem ~/tarkov-data-manager/src/nginx/ssl/

sudo chown -R tdm:tdm ~/tarkov-data-manager/src/nginx/ssl/

# Run a fresh deploy
~/borscht/script/deploy
