name: cache-test

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: src/cache/src/cache/go.mod

      - name: bootstrap
        working-directory: ./src/cache
        run: script/bootstrap

      - name: test
        working-directory: ./src/cache
        run: script/test
