name: cache-acceptance

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  acceptance:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: acceptance
        working-directory: ./src/cache
        run: script/acceptance
