name: restart-vm

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '15 15 * * 1-5'

jobs:
  restart-vm:
    runs-on: ubuntu-latest
    environment: production-secrets

    steps:
      - name: azure login
        uses: azure/login@cb79c773a3cfa27f31f25eb3f677781210c9ce3d # pin@v1.6.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: restart vm
        uses: azure/CLI@4db43908b9df2e7ac93c8275a8f9a448c59338dd # pin@v1.0.9
        with:
          azcliversion: 2.50.0
          inlineScript: |
            az vm restart --resource-group tdm_rg --name tdm_vm
